name: Consume Artifact from Specific Run

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of the workflow to fetch artifact from"
        required: false
        type: string

jobs:
  download:
    runs-on: windows-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        artifact-ids: 3627012139
