name: Consume Artifact from Specific Run

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of the workflow to fetch artifact from"
        required: false
        type: string

jobs:
  download:
    runs-on: windows-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: text-artifact-16563056435
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
        run-id: 16563056435
