name: Generate Artifact

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: |
          echo "This was created in run ID: ${{ github.run_id }}" > data.txt

      - name: Upload artifact with run_id in name
        uses: actions/upload-artifact@v4
        with:
          name: text-artifact-${{ github.run_id }}
          path: data.txt
