name: Robocopy Example

on:
  workflow_dispatch:

jobs:
  robocopy-task:
    runs-on: windows-latest

    steps:
      - name: Create directories and test files
        run: |
          mkdir src\subfolder
          mkdir dest
          mkdir dest\pdbs
          mkdir dest\wincsi\utp

          echo "dummy dll" > src\test.dll
          echo "dummy pdb" > src\test.pdb
          echo "dummy xml" > src\test.xml

      - name: Print important GitHub variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Full ref: $GITHUB_REF"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run Attempt: ${{ github.run_attempt }}"

      - name: Robocopy transfer DLL/XML to dest, PDB to pdbs, $SYSTEM/FD to wincsi/utp
        shell: pwsh
        run: |
          robocopy src dest *.dll *.xml
          $code = $LASTEXITCODE
          Write-Host "Robocopy exit code: $code"
          if ($code -gt 7) { exit $code }
      
          robocopy src dest\pdbs *.pdb
          $code = $LASTEXITCODE
          Write-Host "Robocopy exit code: $code"
          if ($code -gt 7) { exit $code }
      
          robocopy src\$SYSTEM\FD dest\wincsi\utp *.FD0
          $code = $LASTEXITCODE
          Write-Host "Robocopy exit code: $code"
          if ($code -gt 7) { exit $code }

      
          robocopy src\$SYSTEM\FD dest\wincsi\utp *.FD0
          $code = $LASTEXITCODE
          if ($code -gt 7) { exit $code }

