name: Example Workflow
on:
 push:
   branches:
     - '*'
jobs:
 print-ref-name:
   runs-on: ubuntu-latest
   steps:
     - name: Print ref name
       run: echo "The branch or tag name is ${{ github.ref_name }}"
