on:
  workflow_dispatch:

jobs:
  robocopy-task:
    runs-on: windows-latest

    steps:
      - name: Create directories and test files
        run: |
          mkdir src\subfolder
          mkdir dest
          mkdir dest\pdbs
          mkdir dest\wincsi\utp
          echo "dummy dll" > src\test.dll
          echo "dummy pdb" > src\test.pdb
          echo "dummy xml" > src\test.xml
      - name: Print important GitHub variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Full ref: $GITHUB_REF"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
          echo "Job ID: ${{ github.job }}"

  robocopy-task-2:
    runs-on: windows-latest

    steps:
      - name: Print important GitHub variables for robocopy-task-2
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Full ref: $GITHUB_REF"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
          echo "Job ID: ${{ github.job }}"

  robocopy-task-3:
    runs-on: windows-latest

    steps:
      - name: Print important GitHub variables for robocopy-task-3
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Full ref: $GITHUB_REF"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
          echo "Job ID: ${{ github.job }}"
