name: Checkout Dynamic Branch main

on:
  push:
    branches:
      - '**' # Trigger on any branch push
  pull_request:
    branches:
      - '**' # Trigger on pull requests targeting any branch
  workflow_dispatch:

jobs:
  checkout-dynamic-branch:
    name: Checkout Based on Event Type
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Correct Branch Dynamically
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          # Dynamically determine the branch
          ref: ${{ github.event_name == 'push' && github.ref_name || github.event.pull_request.head.ref }}
          
      # Step 2: Display Checked-Out Branch (for debugging)
      - name: Display Checked-Out Branch
        run: |
          echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"
