name: Trigger Build and Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      validate_only:
        description: 'Run validation only?'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  call_build_release:
    uses: ./.github/workflows/build-release.yaml
    with:
      validate_only: ${{ github.event.inputs.validate_only }}
